# Generated by Django 3.0.7 on 2020-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dylnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=2000)),
                ('phone', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('upto', models.DateField()),
                ('dylcount', models.CharField(max_length=10)),
                ('dylrem', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10)),
                ('centre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dylnumber', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('dyldone', models.DateTimeField()),
                ('centre', models.CharField(max_length=100)),
                ('billno', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=150)),
                ('cluster', models.CharField(max_length=150)),
                ('zone', models.CharField(max_length=150)),
                ('dateofreq', models.DateTimeField(blank=True, null=True)),
                ('p1', models.CharField(max_length=150)),
                ('a1', models.CharField(max_length=150)),
                ('h1', models.CharField(max_length=150)),
                ('p2', models.CharField(blank=True, max_length=150, null=True)),
                ('a2', models.CharField(blank=True, max_length=150, null=True)),
                ('h2', models.CharField(blank=True, max_length=150, null=True)),
                ('p3', models.CharField(blank=True, max_length=150, null=True)),
                ('a3', models.CharField(blank=True, max_length=150, null=True)),
                ('h3', models.CharField(blank=True, max_length=150, null=True)),
                ('p4', models.CharField(blank=True, max_length=150, null=True)),
                ('a4', models.CharField(blank=True, max_length=150, null=True)),
                ('h4', models.CharField(blank=True, max_length=150, null=True)),
                ('dist_approve', models.CharField(max_length=150)),
                ('mdcnumber', models.CharField(max_length=150, unique=True)),
                ('otp1', models.CharField(max_length=150)),
                ('otp2', models.CharField(max_length=150)),
                ('otp3', models.CharField(max_length=150)),
                ('otp4', models.CharField(max_length=150)),
                ('lastdat', models.DateField(blank=True, null=True)),
                ('medrem', models.CharField(max_length=50)),
                ('medshop', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=2000)),
                ('phone', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('applytime', models.DateTimeField()),
                ('unit_relate', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_approve', models.CharField(default='PENDING', max_length=10)),
                ('unit_time', models.CharField(max_length=100)),
                ('cluster_approve', models.CharField(default='PENDING', max_length=10)),
                ('cluster_time', models.CharField(max_length=100)),
                ('zonal_approve', models.CharField(default='PENDING', max_length=10)),
                ('zonal_time', models.CharField(max_length=100)),
                ('dist_approve', models.CharField(default='PENDING', max_length=10)),
                ('dist_time', models.CharField(max_length=100)),
                ('dist_feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('dylnumber', models.CharField(max_length=100, unique=True)),
                ('centre', models.CharField(max_length=100)),
            ],
        ),
    ]
