# Generated by Django 3.0.7 on 2020-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_nofdyl'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='form',
            field=models.FileField(default=1, upload_to='form/entry/'),
            preserve_default=False,
        ),
    ]
